### ISSUE TITLE
run the tutorial demo can not get the truth causal graph!

### ISSUE THREAD

**Issue by 945716994** [AArsac/CD_for_TS_with_CBM_and_PMIME#1]
by the way, how to get the lag of each variable on this basis? Ex: x1_t = f(x1_t-1, x2_t-3) , how to know predict x1_t must use x2_t-3 not x2_t-2 or anything else?

**Comment by AArsac** [comment]
Hey,
 have you tried to change the parameters in `run_alg.run_algo()`. On my code it worked with `sig_pmime = 0.04`.
In any case, the algo certainly does not have a 100% success rate.

For your second point, PMIME measures dependence between variables at several time lags. For instance in your example, to decide whether the model is $X1_t = f(X1_{t-1}, X2_{t-3})  or $X1_t = f(X1_{t-1}, X2_{t-2}) it will take the variable that maximises the dependence (in terms of mutual information) between $X2_{t-2}$ and $X1_t$ or between $X2_{t-3}$ and $X1_t$.
But as there is a selection criterion and another computation after this choice, you don't get the exact time lag at the output of the algo, you just get to know whether variable $X2$ contains info on variable $X1$ or not.

Hope this answers your question.

**Comment by 945716994** [comment]
Thanks for your reply! By the way, what does the knnei parameter mean?

**Comment by AArsac** [comment]
To estimate the mutual information (in PMIME), the k-nearest neighbors estimator is used. The knnei param is a coefficient to adjust the number of nearest neighbors (often noted $k$) considered in the estimation. 
For instance if you have a series of size $n=1000$ and you want $k = 10$ then set the parameter knnei to 0.01.

For more details you can e.g. check the paper by J. Runge 2018, Conditional independence testing based on a nearest-neighbor estimator of conditional mutual information
